# syntax=docker.io/docker/dockerfile:1

FROM node:23.11-alpine AS base

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy all files for development
COPY . .

EXPOSE 3000
ENV PORT=3000
ENV NODE_ENV=development
CMD ["yarn", "dev"]